### ISSUE TITLE
SensorPi hangs if not within range of ServerPi

### ISSUE THREAD

**Issue by wolfiex** [cemac/BBSensor#17] opened 2020-11-26 01:17 UTC
Culprit on line `upload_success = upload.sync(SERIAL,db.conn)`. 

The upload function needs a timeout. More debugging of which line is the culprit tomorrow.

**Comment by cemac-ccs** [comment] 2020-11-30 11:31
Error has been tracked to upload/\_\_init\_\_.py in the upload.sync(SERIAL,db.conn) function, when the sftp connection to the serverpi is made. Error is due to no timeout being implemented when connection is being made.

Managed to reproduce error by changing the hostname of the upload target so that it does not match the hostname of the serverpi.
As such, in the field this error could occur when:
1. the serverpi is not set up properly and so has the wrong hostname
1. the sensorpi does not make a successful dns lookup through the raspap software and cannot resolve the hostname
1. the connection drops between the connection test and the upload attempt

or in testing when the sensorpi is connected directly to a router rather than through the serverpi.

Possibilities 1 & 2 can be mitigated by replacing the hostname with the IP address, and this is probably best going forward as the serverpis will likely have different hostnames to differentiate themselves but due to the raspap software they will have the same IP address.

This would not solve possibility 3 however, and so a timeout should be added regardless.

Unfortunately, there is no timeout capability in the declaration of the pysftp.Connection object, and so it is possible that a conversion to the paramiko library might be necessary. This should not be difficult since the pysftp library is a (thin) wrapper over paramiko and so it is already installed on the existing SD card images.

**Comment by cemac-ccs** [comment] 2020-11-30 13:58
Revision to previous - Cannot actually reproduce the error as described.

When I try to reproduce the error, I get an automatic timeout after a while, which retries the connection up to 10 times. Timeout takes around 1 min to trigger and then due to a try/except block the upload retries. DE sent the below logging output vie slack earlier:
```
INFO        ########################################################
INFO        starting 2020-11-26 13:20:00.345706
INFO        ########################################################
INFO        DB saved
INFO        savecondition: 26/11/2020 None
INFO        online
/usr/local/lib/python3.7/dist-packages/pysftp/__init__.py:61: UserWarning: Failed to load HostKeys from /root/.ssh/known_hosts.  You will need to explicitly load HostKeys (cnopts.hostkeys.load(filename)) or disableHostKey checking (cnopts.hostkeys = None).
  warnings.warn(wmsg, UserWarning)
INFO        Upload failed - attempt 1 of 10
Error - ('BBServer1-1.local', 22)
Retrying
INFO        Upload failed - attempt 2 of 10
Error - ('BBServer1-1.local', 22)
Retrying
```
Looking at this output, it seems that this error has been being handled correctly and timing out, as it is returning "Upload failed - attempt # of 10" when it fails, however the fact that the connection timed out does not appear in the exception so it was not clear that a timeout was being encountered. As such I think, at least for establishing the connection, that this issue isn't actually a problem, however this issue has highlighted that sftp commands are being called with no timeout and this could conceivably create a problem in situations where the connection object is successfully created but the connection drops before upload can be completed. This can be added easily by putting `srv.timeout(10.0)` as the first line after the connection object is defined.

**Comment by cemac-ccs** [comment] 2021-02-17 12:12
Suggested fix (srv.timeout) actually broke connectivity.

A different fix is in process, where uploads to the server are dependent on a test of connectivity to the _server_, rather than a test of connectivity to the _internet_. time updates and git pulls are still dependent on connectivity to the internet. PR will be generated and attached to this ticket

**Comment by cemac-ccs** [comment] 2021-02-19 12:21
PR has been merged in, and so this issue will be closed if testing is successful

**Closed** 2021-05-12 16:47 UTC
Labels: bug
